#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["VueServer.Main/VueServer.Main.csproj", "VueServer.Main/"]
COPY ["VueServer.Core/VueServer.Core.csproj", "VueServer.Core/"]
COPY ["VueServer.Domain/VueServer.Domain.csproj", "VueServer.Domain/"]
COPY ["VueServer.Modules.Core/VueServer.Modules.Core.csproj", "VueServer.Modules.Core/"]
COPY ["VueServer.Modules.Chat/VueServer.Modules.Chat.csproj", "VueServer.Modules.Chat/"]
COPY ["VueServer.Modules.Directory/VueServer.Modules.Directory.csproj", "VueServer.Modules.Directory/"]
COPY ["VueServer.Modules.Library/VueServer.Modules.Library.csproj", "VueServer.Modules.Library/"]
COPY ["VueServer.Modules.Weight/VueServer.Modules.Weight.csproj", "VueServer.Modules.Weight/"]
RUN dotnet restore "./VueServer.Main/VueServer.Main.csproj"
COPY . .
WORKDIR "/src/VueServer.Main"
RUN dotnet build "./VueServer.Main.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./VueServer.Main.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VueServer.Main.dll"]