export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'

export const JWT_TOKEN_CREATE = 'JWT_TOKEN_CREATE'
export const JWT_TOKEN_DESTROY = 'JWT_TOKEN_DESTROY'
export const REFRESH_TOKEN_CREATE = 'REFRESH_TOKEN_CREATE'
export const REFRESH_TOKEN_DESTROY = 'REFRESH_TOKEN_DESTROY'

export const CSRF_CREATE = 'CSRF_TOKEN_CREATE'
export const CSRF_DESTROY = 'CSRF_TOKEN_DESTROY'

