#client
FROM node:latest

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./vue-server-ui/package.json ./
RUN npm install
COPY --chown=node:node ./vue-server-ui ./

CMD ["npm", "run", "dev"]